version: '3'

services:
  nginx:
    build: ./dockerfiles/nginx/
    volumes:
      - ./dockerfiles/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.audit.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.audit.entrypoints=web"
      - "traefik.http.routers.audit-secured.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.audit-secured.entrypoints=web-secured"
      - "traefik.http.routers.audit-secured.tls=true"
  php-fpm:
    build: ./dockerfiles/php-fpm/
    volumes:
      - ./src:/var/www/html
      - ~/.composer:/.composer
    user: 1000:1000
  mariadb:
    image: mariadb:latest
    volumes: 
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
  web:
    external: true

volumes:
  mariadb: